CREATE TYPE resource_rating AS ENUM (1, 2, 3, 4, 5);
CREATE TYPE resource_level AS TEXT('Beginner', 'Intermediate', 'Advanced');
CREATE TYPE resource_cost AS TEXT ('Free', 'Paid');
CREATE TYPE resource_type AS TEXT ('Textbook', 'Workbook', 'Storybook', 'Course', 'Website');

CREATE TABLE resources(
  id INTEGER PRIMARY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  image_link TEXT NOT NULL,
  language TEXT NOT NULL,
  level resource_level NOT NULL,
  type resource_type NOT NULL,
  rating resource_rating NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  cost resource_cost NOT NULL
);