CREATE TYPE resource_rating AS ENUM ('1', '2', '3', '4', '5');
-- CREATE TYPE resource_level AS ('Beginner', 'Intermediate', 'Advanced');
-- CREATE TYPE resource_cost AS ('Free', 'Paid');
-- CREATE TYPE resource_type AS ('Textbook', 'Workbook', 'Storybook', 'Course', 'Website');

CREATE TABLE resources(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  image_link TEXT NOT NULL,
  language TEXT NOT NULL,
  level TEXT NOT NULL,
  type TEXT NOT NULL,
  rating resource_rating NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  cost TEXT NOT NULL
);