INSERT INTO resources (title, image_link, language, level, type, rating, url, cost, description)
VALUES 
('Korean Made Simple: A beginner guide to learning the Korean language', 'https://images-na.ssl-images-amazon.com/images/I/51JwrB7zAcL._SX348_BO1,204,203,200_.jpg', 'Korean', 'Beginner', 'Textbook', '4', 'https://www.amazon.com/Korean-Made-Simple-beginners-learning/dp/1497445825', 'Paid', 'None'),
('Talk to me in Korean', 'https://cdn.talktomeinkorean.com/wp-content/uploads/2019/11/17144847/set_Level-1-Package.jpg', 'Korean', 'Beginner', 'Textbook, Workbook', '5', 'https://talktomeinkorean.com/product/lv1p/', 'Paid', 'Well Balanced Progression. Each lesson teaches a focused and comprehendible concept that can easily be understood and applied. Additionally, sample sentences really help illustrate the bounds of the given word or concept. It is another helpful progression in the series. I would highly recommend it to anyone.'),
('How To Study Korean', 'https://www.howtostudykorean.com/wp-content/uploads/2018/01/FinalBanner2015.png', 'Korean', 'Beginner, Intermediate', 'Website', '4', 'https://www.howtostudykorean.com/', 'Free', 'The purpose of this website is to provide Korean learners with a one-stop resource for learning Korean. We strive to provide the most detailed, accurate and clear explanations at every step of the way – from learning how to read all the way to advanced grammar. Our lessons will always be free and are chuck-full of content. You wouldn’t believe how much is in there. As a base, each lesson includes: Twenty to thirty vocabulary words, grammar tailored to the specific level of study applying the vocabulary from that lesson, audio recordings of every Korean word and sentences'),
('The French Experiment', 'https://uploads-ssl.webflow.com/587ed23fdf37ace65c3a60fa/58800d9eff88730b37105140_frenchexperiment-logo-lrg.png', 'French', 'Beginner, Intermediate', 'Website', '5', 'https://www.thefrenchexperiment.com', 'Free', 'Website with free lessons and stories to learn French.'),
('Practice Makes Perfect: Basic French, Premium Second Edition', 'https://images-na.ssl-images-amazon.com/images/I/515Ay4ui3IL._SX389_BO1,204,203,200_.jpg', 'French', 'Beginner', 'Textbook', '4', 'https://www.amazon.com/Practice-Makes-Perfect-French-Premium/dp/1259836398/ref=asc_df_1259836398/?tag=hyprod-20&linkCode=df0&hvadid=241995309321&hvpos=&hvnetw=g&hvrand=3145720493198348420&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9019546&hvtargid=pla-431859876365&psc=1', 'Paid', 'None'),
('En Espanol-Level 1', 'https://img.thriftbooks.com/api/images/m/43b30bce375d76d7244b3605b9d1d59356832a09.jpg', 'Spanish', 'Beginner', 'Textbook', '5', 'https://www.thriftbooks.com/w/en-espanol-level-1_estella-gahala/247593/item/4039344/?mkwid=%7cdc&pcrid=494412958018&pkw=&pmt=&slid=&plc=&pgrid=119960546627&ptaid=pla-1151316948670&gclid=Cj0KCQjwo-aCBhC-ARIsAAkNQiv0d7-Cwjxq4ImFH5BCif6Y1hsR5QFvsqY4gjIVI52IUtA6_Al3FvsaAm7LEALw_wcB#idiq=4039344&edition=3387800', 'Paid', 'I was taught with this book and I bought it to study over the summer. It is great for learning spanish. The order some subjects come up is a bit odd, but it is a great textbook. I suggest buying one of the used copies (which are generally in really good condition) to save around $70.' ),
('Advanced Spanish Grammar', 'https://images-na.ssl-images-amazon.com/images/I/51LFLuo2bfL._SX404_BO1,204,203,200_.jpg', 'Spanish', 'Advanced', 'Textbook', '5', 'https://www.amazon.com/Advanced-Spanish-Grammar-Self-Teaching-Second/dp/0471134481?tag=fluentu-20', 'Paid', 'This complete, accessible guide clarifies grammatical structure and explains vocabulary usage to help you master Spanish. Whether you need extra help for a course, want a quick review for a test, or simply want to brush up your language skills, this is the book to have.'),
('SwahiliPod101', 'https://cdn.innovativelanguage.com/swahilipod101/static/images/google_landing_page/tools_Swahili.png', 'Swahili', 'Beginner, Intermediate, Advanced', 'Website','4', 'https://www.swahilipod101.com/', 'Free, Paid', 'Has video lessons, study tools and individual teacher guidance.');

