INSERT INTO resources (user_id, title, image_link, language, level, type, rating, url, cost, description)
VALUES 
(1, 'Korean Made Simple: A beginner guide to learning the Korean language', 'https://images-na.ssl-images-amazon.com/images/I/51JwrB7zAcL._SX348_BO1,204,203,200_.jpg', 'Korean', 'Beginner', 'Textbook', 4, 'https://www.amazon.com/Korean-Made-Simple-beginners-learning/dp/1497445825', 'Paid', 'Learn the Korean writing system, Korean culture, and even history. Learn over 1,000 vocabulary words and phrases through 20 in-depth and fun lessons, filled with plenty of examples. Additionally, practice sections with answer keys are built into every chapter.

This book also contains additional advanced level notes for more skilled Korean speakers looking for a review of basic grammar and concepts, including a full appendix covering sound change rules.'),
(2, 'Talk to me in Korean', 'https://cdn.talktomeinkorean.com/wp-content/uploads/2019/11/17144847/set_Level-1-Package.jpg', 'Korean', 'Beginner', 'Textbook', 5, 'https://talktomeinkorean.com/product/lv1p/', 'Paid', 'Well Balanced Progression. Each lesson teaches a focused and comprehendible concept that can easily be understood and applied. Additionally, sample sentences really help illustrate the bounds of the given word or concept. It is another helpful progression in the series. I would highly recommend it to anyone.'),
(1, 'How To Study Korean', 'https://www.howtostudykorean.com/wp-content/uploads/2018/01/FinalBanner2015.png', 'Korean', 'Beginner, Intermediate', 'Website', 4, 'https://www.howtostudykorean.com/', 'Free', 'The purpose of this website is to provide Korean learners with a one-stop resource for learning Korean. We strive to provide the most detailed, accurate and clear explanations at every step of the way – from learning how to read all the way to advanced grammar. Our lessons will always be free and are chuck-full of content. You wouldn’t believe how much is in there. As a base, each lesson includes: Twenty to thirty vocabulary words, grammar tailored to the specific level of study applying the vocabulary from that lesson, audio recordings of every Korean word and sentences'),
(2, 'The French Experiment', 'https://uploads-ssl.webflow.com/587ed23fdf37ace65c3a60fa/58800d9eff88730b37105140_frenchexperiment-logo-lrg.png', 'French', 'Beginner, Intermediate', 'Website', 5, 'https://www.thefrenchexperiment.com', 'Free', 'Website with free lessons and stories to learn French.'),
(2, 'Practice Makes Perfect: Basic French, Premium Second Edition', 'https://images-na.ssl-images-amazon.com/images/I/515Ay4ui3IL._SX389_BO1,204,203,200_.jpg', 'French', 'Beginner', 'Textbook', 4, 'https://www.amazon.com/Practice-Makes-Perfect-French-Premium/dp/1259836398/ref=asc_df_1259836398/?tag=hyprod-20&linkCode=df0&hvadid=241995309321&hvpos=&hvnetw=g&hvrand=3145720493198348420&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9019546&hvtargid=pla-431859876365&psc=1', 'Paid', 'Practice Makes Perfect: Basic French is the proven companion to your French-learning experience. In each bite-sized lesson, author Eliane Kurbegov explains one―and only one―grammar concept and illustrates it with clear examples. These lessons are purposefully short, so you can complete them in twenty minutes or less, and go at a pace that works for you.'),
(1, 'En Espanol-Level 1', 'https://img.thriftbooks.com/api/images/m/43b30bce375d76d7244b3605b9d1d59356832a09.jpg', 'Spanish', 'Beginner', 'Textbook', 5, 'https://www.thriftbooks.com/w/en-espanol-level-1_estella-gahala/247593/item/4039344/?mkwid=%7cdc&pcrid=494412958018&pkw=&pmt=&slid=&plc=&pgrid=119960546627&ptaid=pla-1151316948670&gclid=Cj0KCQjwo-aCBhC-ARIsAAkNQiv0d7-Cwjxq4ImFH5BCif6Y1hsR5QFvsqY4gjIVI52IUtA6_Al3FvsaAm7LEALw_wcB#idiq=4039344&edition=3387800', 'Paid', 'I was taught with this book and I bought it to study over the summer. It is great for learning spanish. The order some subjects come up is a bit odd, but it is a great textbook. I suggest buying one of the used copies (which are generally in really good condition) to save around $70.' ),
(3, 'Advanced Spanish Grammar', 'https://images-na.ssl-images-amazon.com/images/I/51LFLuo2bfL._SX404_BO1,204,203,200_.jpg', 'Spanish', 'Advanced', 'Textbook', 5, 'https://www.amazon.com/Advanced-Spanish-Grammar-Self-Teaching-Second/dp/0471134481?tag=fluentu-20', 'Paid', 'This complete, accessible guide clarifies grammatical structure and explains vocabulary usage to help you master Spanish. Whether you need extra help for a course, want a quick review for a test, or simply want to brush up your language skills, this is the book to have.'),
(2, 'SwahiliPod101', 'https://cdn.innovativelanguage.com/swahilipod101/static/images/google_landing_page/tools_Swahili.png', 'Swahili', 'Beginner, Intermediate, Advanced', 'Website', 4, 'https://www.swahilipod101.com/', 'Free, Paid', 'Has video lessons, study tools and individual teacher guidance.'),
(1, 'Plataforma de Português Online', 'https://www.acm.gov.pt/acm-main-theme/images/popup/logo_popup.png', 'Portuguese', 'Beginner', 'Website', 4, 'https://pptonline.acm.gov.pt/', 'Free', 'Website created by Portuguese Government to help immigrants learn Portuguese. The format is comparable to Busuu for European Portuguese, with 24 themed modules divided between Elementary and Independent levels of practice. Each module come with its own targets stated at the beginning, which helps you assess if you got the most out of it or if you need to revisit it.'),
(2, 'Portuguese With Carla', 'https://portuguesewithcarla.com/wp-content/uploads/2020/12/logo_150.svg', 'Portuguese', 'Intermediate', 'Class', 5, 'https://portuguesewithcarla.com/', 'Paid', 'I first encountered Carla and her web site ptwithcarla.com, when I was searching for sources to learn European Portuguese. The site was easy to navigate and useful. I also found her podcast lessons and gave them a try. They were not long, but not short either. Just the right length in time, with enough words, phrases and useful information to get you started.' ),
(1, 'Easy Spanish Step By Step', 'https://images-na.ssl-images-amazon.com/images/I/51D9GPpx0AL._SX391_BO1,204,203,200_.jpg', 'Spanish', 'Beginner', 'Textbook', 4, 'https://www.amazon.com/Spanish-Step-Step-Barbara-Bregstein/dp/0071463380', 'Paid', 'Easy Spanish Step by Step proves that a solid grounding in grammar basics is the key to mastering a second language. Grammatical rules and concepts are clearly explained in order of importance, and more than 300 verbs and key terms are introduced on the basis of frequency. Numerous exercises and engaging readings help learners quickly build their Spanish speaking and comprehension prowess.');
